runtime: php
handlers:
- url: /(.*)
  secure: always
  redirect_http_response_code: 301
  script: auto

- url: /.*
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  script: auto
